# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mainstream
email: go@mainstre.am
description: > # this means to ignore newlines until "baseurl:"
  Work with images and share them with the world on Mainstream.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://mainstre.am" # the base hostname & protocol for your site
twitter_username: goMainstream
github_username:  goMainstream
shareImage: "http://shootsofficial.com/shootsofficial.assets/images/shoots-jasonhargrove-stella-portrait-rake.jpeg"
contactEmail: go@mainstre.am

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
exclude: ['node_modules', 'assets/css/main.scss', 'gulpfile.js', 'README.md', 'webpack.config.js']
